const COLOR_SELECTED_NONE = "COLOR_SELECTED_NONE"
const ACTIVE_CIRCLE_COLOR_DEFAULT = "blue"
const COLOR_SELECTION_NAME_NONE = "COLOR_SELECTION_NAME_NONE"

// Active circle Types
const CIRCLE_ONE_ACTIVE = "CIRCLE_ONE_ACTIVE"
const CIRCLE_TWO_ACTIVE = "CIRCLE_TWO_ACTIVE"
const CIRCLE_THREE_ACTIVE = "CIRCLE_THREE_ACTIVE"
const CIRCLE_FOUR_ACTIVE = "CIRCLE_FOUR_ACTIVE"
const CIRCLE_FIVE_ACTIVE = "CIRCLE_FIVE_ACTIVE"
const CIRCLE_ACTIVE_NONE = "CIRCLE_ACTIVE_NONE"

// const initialColorSelection = {
//     colorCircle_1: COLOR_SELECTED_NONE,
//     colorCircle_2: COLOR_SELECTED_NONE,
//     colorCircle_3: COLOR_SELECTED_NONE,
//     colorCircle_4: COLOR_SELECTED_NONE,
//     colorCircle_5: COLOR_SELECTED_NONE
// }

// Circle IDs
const CIRCLE_ONE_ID = "CIRCLE_ONE_ID"
const CIRCLE_TWO_ID = "CIRCLE_TWO_ID"
const CIRCLE_THREE_ID = "CIRCLE_THREE_ID"
const CIRCLE_FOUR_ID = "CIRCLE_FOUR_ID"
const CIRCLE_FIVE_ID = "CIRCLE_FIVE_ID"

const initialColorSelection = [
    {id: CIRCLE_ONE_ID, color: COLOR_SELECTED_NONE },
    {id: CIRCLE_TWO_ID, color: COLOR_SELECTED_NONE },
    {id: CIRCLE_THREE_ID, color: COLOR_SELECTED_NONE },
    {id: CIRCLE_FOUR_ID, color: COLOR_SELECTED_NONE },
    {id: CIRCLE_FIVE_ID, color: COLOR_SELECTED_NONE }
]

export {
    ACTIVE_CIRCLE_COLOR_DEFAULT,
    COLOR_SELECTION_NAME_NONE,
    CIRCLE_ONE_ACTIVE,
    CIRCLE_TWO_ACTIVE,
    CIRCLE_THREE_ACTIVE,
    CIRCLE_FOUR_ACTIVE,
    CIRCLE_FIVE_ACTIVE,
    CIRCLE_ACTIVE_NONE,
    initialColorSelection
}